name: kAFKA Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  run-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Decode Base64 secret to a variable (Python dict)
        id: decode_config
        run: |
          decoded=$(echo "${{ secrets.clusterConfMapping }}" | base64 --decode)
          echo $decoded
          # Remove newlines if needed
          clean_decoded=$(echo "$decoded" | tr -d '\n')
          echo "config=$clean_decoded" >> $GITHUB_OUTPUT

      - name: Run Kafka Integration
        uses: port-labs/ocean-sail@v1
        with:
          type: kafka
          port_client_id: ${{ secrets.PORT_CLIENT_ID }}
          port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
          port_base_url: "https://api.port.io"
          config: ${{ steps.decode_config.outputs.config }}
