name: kAFKA Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  run-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Run Kafka Integration
        uses: port-labs/ocean-sail@v1
        with:
          type: kafka
          port_client_id: ${{ secrets.PORT_CLIENT_ID }}
          port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
          port_base_url: "https://api.port.io"
          config: ${{ secrets.OCEAN__INTEGRATION__CONFIG__CLUSTER_CONF_MAPPING }}
