name: kAFKA Workflow
on:
    workflow_dispatch:
    schedule:
        - cron: '0 */1 * * *' # Determines the scheduled interval for this workflow. This example runs every hour.

jobs:
    run-integration:
        runs-on: ubuntu-latest
        timeout-minutes: 30 # Set a time limit for the job	
        steps:
            - name: Run kafka Integration
              uses: port-labs/ocean-sail@v1
              with:
                type: kafka
                port_client_id: ${{ secrets.PORT_CLIENT_ID }}
                port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
                port_base_url: "https://api.port.io"
                config: |
                    cluster_conf_mapping: ${{ secrets.clusterConfMapping }}
